# Generated by Django 4.0.4 on 2022-06-10 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='conductor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('cedula', models.CharField(max_length=10, verbose_name='Cedula')),
                ('telefono', models.CharField(max_length=10, verbose_name='Telefono')),
                ('direccion', models.CharField(max_length=20, verbose_name='Direccion')),
                ('ciudad', models.CharField(max_length=20, verbose_name='Ciudad')),
                ('placa', models.ImageField(upload_to='imagenes/', verbose_name='Placa')),
            ],
        ),
    ]
