# Generated by Django 4.0.4 on 2022-06-15 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfinal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=50)),
                ('clave', models.CharField(max_length=50)),
            ],
        ),
    ]
